line-length = 100
target-version = "py311"
extend-exclude = ["**/.venv", "**/__pycache__"]

src = ["apps/api/src", "apps/worker/src"]

[lint]
select = ["E", "F", "I", "B", "UP", "C4"]
ignore = ["E203", "E501"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
