name: mb-dev

services:
  db:
    image: postgres:16
    container_name: mb_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mb_dev}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-mb_dev}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: mb_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile.dev
    container_name: mb_api
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/mb_dev}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      # MB_AUTH_* come from env_file; don't redeclare here to avoid blank warnings
    working_dir: /workspace/apps/api
    volumes:
      - ../..:/workspace
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    image: node:20-bookworm-slim
    container_name: mb_web
    env_file:
      - ../../.env
    working_dir: /workspace
    environment:
      CI: "1"
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"
      PNPM_HOME: "/usr/local/share/pnpm"
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      INTERNAL_API_URL: ${INTERNAL_API_URL:-http://api:8000}
    volumes:
      - ../..:/workspace:cached
      - /workspace/node_modules
      - /workspace/apps/web/node_modules
      - /workspace/.pnpm-store
      - /workspace/apps/web/.next
    command: >
      bash -lc "
        set -euo pipefail &&
        apt-get update &&
        # curl for healthcheck + procps/iproute2 for debugging (ps/ss)
        apt-get install -y --no-install-recommends curl procps iproute2 python3 make g++ ca-certificates &&
        rm -rf /var/lib/apt/lists/* &&
        corepack enable &&
        corepack prepare pnpm@9 --activate &&
        pnpm config set store-dir /workspace/.pnpm-store &&
        pnpm config set ignore-scripts false &&
        pnpm install --no-frozen-lockfile --force &&
        pnpm --filter web dev -H 0.0.0.0 -p 3000
      "
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  pgdata:
