"""Add canonical odds schema for Australian bookmakers

Revision ID: 26fde4226a2f
Revises: f9a0806a3788
Create Date: 2025-09-28 11:49:03.518662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fde4226a2f'
down_revision: Union[str, Sequence[str], None] = 'f9a0806a3788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('website_url', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('supports_each_way', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('default_source_type', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=True),
    sa.Column('api_endpoint', sa.String(length=200), nullable=True),
    sa.Column('rate_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('scraping_config', sa.JSON(), nullable=True),
    sa.Column('last_successful_scrape', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmakers_code'), 'bookmakers', ['code'], unique=True)
    op.create_index(op.f('ix_bookmakers_id'), 'bookmakers', ['id'], unique=False)
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('season_format', sa.JSON(), nullable=True),
    sa.Column('common_markets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_code'), 'sports', ['code'], unique=True)
    op.create_index(op.f('ix_sports_id'), 'sports', ['id'], unique=False)
    op.create_table('bookmaker_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('rate_limit_ms', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('average_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count_24h', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_bookmaker_active', 'bookmaker_sources', ['bookmaker_id', 'is_active'], unique=False)
    op.create_index('idx_source_type_active', 'bookmaker_sources', ['source_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_bookmaker_sources_id'), 'bookmaker_sources', ['id'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_competition_sport_active', 'competitions', ['sport_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('name_variations', sa.JSON(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'canonical_name', name='uq_team_sport_canonical')
    )
    op.create_index('idx_team_sport_active', 'teams', ['sport_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_competition_start', 'events', ['competition_id', 'start_time'], unique=False)
    op.create_index('idx_event_status_start', 'events', ['status', 'start_time'], unique=False)
    op.create_index('idx_event_teams', 'events', ['home_team_id', 'away_team_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_active_closes', 'markets', ['is_active', 'closes_at'], unique=False)
    op.create_index('idx_market_event_type', 'markets', ['event_id', 'market_type'], unique=False)
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('selection_key', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'selection_key', name='uq_selection_market_key')
    )
    op.create_index('idx_selection_market_key', 'selections', ['market_id', 'selection_key'], unique=False)
    op.create_index(op.f('ix_selections_id'), 'selections', ['id'], unique=False)
    op.create_table('odds_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('best_back_selection_id', sa.Integer(), nullable=False),
    sa.Column('best_back_bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('best_back_odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('best_lay_selection_id', sa.Integer(), nullable=False),
    sa.Column('best_lay_bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('best_lay_odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('arbitrage_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('profit_margin_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recommended_stake_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('update_frequency_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['best_back_bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['best_back_selection_id'], ['selections.id'], ),
    sa.ForeignKeyConstraint(['best_lay_bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['best_lay_selection_id'], ['selections.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comparison_arbitrage_active', 'odds_comparisons', ['arbitrage_percentage', 'is_active'], unique=False)
    op.create_index('idx_comparison_calculated', 'odds_comparisons', ['calculated_at'], unique=False)
    op.create_index('idx_comparison_expires', 'odds_comparisons', ['expires_at'], unique=False)
    op.create_index('idx_comparison_market_active', 'odds_comparisons', ['market_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_odds_comparisons_id'), 'odds_comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_odds_comparisons_is_active'), 'odds_comparisons', ['is_active'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('market_status', sa.String(length=20), nullable=True),
    sa.Column('available_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('scrape_session_id', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_id', 'bookmaker_id', 'timestamp', name='uq_odds_selection_bookmaker_time')
    )
    op.create_index('idx_odds_bookmaker_current', 'odds_snapshots', ['bookmaker_id', 'is_current'], unique=False)
    op.create_index('idx_odds_selection_bookmaker_current', 'odds_snapshots', ['selection_id', 'bookmaker_id', 'is_current'], unique=False)
    op.create_index('idx_odds_selection_current', 'odds_snapshots', ['selection_id', 'is_current'], unique=False)
    op.create_index('idx_odds_timestamp', 'odds_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_id'), 'odds_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_is_current'), 'odds_snapshots', ['is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_snapshots_is_current'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_id'), table_name='odds_snapshots')
    op.drop_index('idx_odds_timestamp', table_name='odds_snapshots')
    op.drop_index('idx_odds_selection_current', table_name='odds_snapshots')
    op.drop_index('idx_odds_selection_bookmaker_current', table_name='odds_snapshots')
    op.drop_index('idx_odds_bookmaker_current', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_odds_comparisons_is_active'), table_name='odds_comparisons')
    op.drop_index(op.f('ix_odds_comparisons_id'), table_name='odds_comparisons')
    op.drop_index('idx_comparison_market_active', table_name='odds_comparisons')
    op.drop_index('idx_comparison_expires', table_name='odds_comparisons')
    op.drop_index('idx_comparison_calculated', table_name='odds_comparisons')
    op.drop_index('idx_comparison_arbitrage_active', table_name='odds_comparisons')
    op.drop_table('odds_comparisons')
    op.drop_index(op.f('ix_selections_id'), table_name='selections')
    op.drop_index('idx_selection_market_key', table_name='selections')
    op.drop_table('selections')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_index('idx_market_event_type', table_name='markets')
    op.drop_index('idx_market_active_closes', table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('idx_event_teams', table_name='events')
    op.drop_index('idx_event_status_start', table_name='events')
    op.drop_index('idx_event_competition_start', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index('idx_team_sport_active', table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_index('idx_competition_sport_active', table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_bookmaker_sources_id'), table_name='bookmaker_sources')
    op.drop_index('idx_source_type_active', table_name='bookmaker_sources')
    op.drop_index('idx_source_bookmaker_active', table_name='bookmaker_sources')
    op.drop_table('bookmaker_sources')
    op.drop_index(op.f('ix_sports_id'), table_name='sports')
    op.drop_index(op.f('ix_sports_code'), table_name='sports')
    op.drop_table('sports')
    op.drop_index(op.f('ix_bookmakers_id'), table_name='bookmakers')
    op.drop_index(op.f('ix_bookmakers_code'), table_name='bookmakers')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
