"""Add normalized_name column to events table for cross-bookmaker matching

Revision ID: ad28040a33b6
Revises: 20251227_prod_indexes
Create Date: 2026-01-07 10:23:18.909388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad28040a33b6'
down_revision: Union[str, Sequence[str], None] = '20251227_prod_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bookmaker_code_active'), table_name='bookmakers', postgresql_where='(is_active = true)')
    op.add_column('events', sa.Column('normalized_name', sa.String(length=200), nullable=True))
    op.drop_index(op.f('idx_events_past_cleanup'), table_name='events')
    op.drop_index(op.f('idx_events_upcoming'), table_name='events', postgresql_where="((status)::text = 'scheduled'::text)")
    op.create_index('idx_event_normalized', 'events', ['competition_id', 'normalized_name', 'start_time'], unique=False)
    op.drop_index(op.f('idx_odds_current_only'), table_name='odds_snapshots', postgresql_where='(is_current = true)')
    op.drop_index(op.f('idx_odds_matcher_covering'), table_name='odds_snapshots', postgresql_where='(is_current = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_odds_matcher_covering'), 'odds_snapshots', ['selection_id', 'bookmaker_id', 'decimal_odds', 'available_amount'], unique=False, postgresql_where='(is_current = true)')
    op.create_index(op.f('idx_odds_current_only'), 'odds_snapshots', ['selection_id', 'bookmaker_id'], unique=False, postgresql_where='(is_current = true)')
    op.drop_index('idx_event_normalized', table_name='events')
    op.create_index(op.f('idx_events_upcoming'), 'events', ['competition_id', 'start_time'], unique=False, postgresql_where="((status)::text = 'scheduled'::text)")
    op.create_index(op.f('idx_events_past_cleanup'), 'events', ['start_time'], unique=False)
    op.drop_column('events', 'normalized_name')
    op.create_index(op.f('idx_bookmaker_code_active'), 'bookmakers', ['code'], unique=False, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
